apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: msvc_usuarios
#  username: root
#  password: mintic21
  curso_url: "msvc-cursos:8002"
  application.yaml: |-
    config:
      texto: configurando ambiente por defecto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres14:5432"
  database: msvc_cursos
#  username: danielesteban
#  password: danielesteban
  usuario_url: "msvc-usuarios:8001"