apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - image: hawk867/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP