apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  username: cm9vdA==
  password: bWludGljMjE=

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: ZGFuaWVsZXN0ZWJhbg==
  password: ZGFuaWVsZXN0ZWJhbg==